; special text IDs
DEF TEXT_MON_FAINTED      EQU $d0
DEF TEXT_BLACKED_OUT      EQU $d1
DEF TEXT_REPEL_WORE_OFF   EQU $d2
DEF TEXT_SAFARI_GAME_OVER EQU $d3

; PrintNumber
DEF BIT_MONEY_SIGN     EQU 5
DEF BIT_LEFT_ALIGN     EQU 6
DEF BIT_LEADING_ZEROES EQU 7

DEF MONEY_SIGN EQU     (1 << BIT_MONEY_SIGN)
DEF LEFT_ALIGN EQU     (1 << BIT_LEFT_ALIGN)
DEF LEADING_ZEROES EQU (1 << BIT_LEADING_ZEROES)
