; Elemental types
;physical types
DEF NORMAL   EQU $00
DEF FIGHTING EQU $01
DEF FLYING   EQU $02
DEF POISON   EQU $03
DEF GROUND   EQU $04
DEF ROCK     EQU $05
DEF BIRD	 EQU $06	;joenote - added-in this unused type
DEF BUG      EQU $07
DEF DRAGON   EQU $08
DEF STEEL    EQU $09

;special types
DEF FIRE     EQU $14
DEF WATER    EQU $15
DEF GRASS    EQU $16
DEF ELECTRIC EQU $17
DEF PSYCHIC  EQU $18
DEF ICE      EQU $19
DEF GHOST    EQU $1A
DEF DARK     EQU $1B